springdoc:
  packages-to-scan: com.geupjo.koreantiger.controller
  api-docs:
    path: /docs
    groups.enabled: false
  swagger-ui:
    path: /swagger/ui
    display-request-duration: true
    display-operation-id: true
    syntax-highlight.theme: monokai
    doc-expansion: none

---

# local config
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
---
# dev config
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
---
# prod config
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    enabled: false
