version: "3"
services:
  postgresql:
    ## 버전을 정의 필요
    image: postgres
    restart: always
    container_name: tigerDB
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data